# Generated by Django 2.2.5 on 2020-02-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
