# Generated by Django 2.2.5 on 2020-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_userrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelationship',
            name='selfname',
            field=models.CharField(max_length=50),
        ),
    ]
