# Generated by Django 2.2.5 on 2020-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_auto_20200224_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfname', models.CharField(max_length=50)),
                ('blockname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='friendname',
            field=models.CharField(max_length=50),
        ),
    ]
